cc_test(
  name = "BattleShipBoard",
  size = "small",
  srcs = ["BattleShipBoardTest.cc"],
  deps = ["@com_google_googletest//:gtest_main", "//main:BattleShipBoard"],
)

cc_test(
  name = "BoardTextViewTest",
  size = "small",
  srcs = ["BoardTextViewTest.cc"],
  deps = ["@com_google_googletest//:gtest_main", "//main:BattleShipBoard", "//main:BoardTextView"],
)